# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 67908ea0fa13794916e5ea0a94cfe2e0c733b60be48cef3bc591e77861699a4ce741a8351e2d5a8b1fa1536b3b4ee5864ea9bf0795a34175edf2083e8de259d3

test:
  secret_key_base: 05f448770e0edfa41e8a94a593650b7edb013b202b590de8963c68f5dced53493dce2e32f6e919e4099ea4300786d6ea18f277d880921822103b499267f377d6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
